### PR TITLE
Remove redundant and unwanted build checks

### PR DESCRIPTION
**Pull request by abhijeetk**
Currently, wolvic/BUILD.gn is accessible only to Android builds through an `assert(is_android)` check. This change removes unnecessary build configurations that were previously guarded by `is_android` an `is_fuchsia`, as they no longer seem relevant.

### CODE REVIEW

**Review by ns-mshin — APPROVED** [review]

**Comment by abhijeetk** [comment]
@ns-mshin which option should I choose to merge commit ? 
- Squash and Merge or
- Rebase and merge

**Review by svillar — CHANGES_REQUESTED** [review]
A few comments
1. remove the [wolvic] prefix from title
2. either mention that you're also sorting the deps or move that change to a different commit
3. Do not include extra blanks (see `:pak`)

**Review by abhijeetk — COMMENTED** [review]
TAs per review comment only added changes related to removing redundant and unwanted build checks. I will push separate PR for reordering on deps target.

**Comment by ns-mshin** [comment]
Hi, @abhijeetk, If you stack patches in your PR to address review comments, I'd like to suggest Squash and Merge. And if you stack them to handle different objective in same PR, it would be nice to rebase & merge to leave the patch's history in git. wdyt?

**Pull request merged**
