### PR TITLE
[WebXR] Fix the stuck flow

### PR DESCRIPTION
**Pull request by mshin-wolvic**
The stuck flow issue is where new frame information is not gotten when SubmitFrameMissing is notified from the renderer.
This patch adds a pending callback to prevent the sequence from stuck.

### CODE REVIEW

**Review by svillar — CHANGES_REQUESTED** [review]
Many thanks for the awesome patch. I've a few comments:

* Please remove the `Fixes #133` from the commit message as that refers to an internal tool. Future readers might be confused. Perhaps you could instead add the URL of the WebXR sample that you're using for testing
* Would it be possible to split it in two commits? One for the sync_frame_index_ changes and the other one for the pending_getframedata_ changes. I think they can be two different commits but please correct me if I'm wrong.
* I tested it and I wonder whether what we're doing is correct because it's "too good". All the other browsers (Wolvic Gecko, Meta browser) do suffer severe performance penalties because we're indeed skipping frames. However when testing this patch everything is supersmooth and we barely lose 10-20 FPS even moving the slider to 11 frames skipped. So I wonder whether we might be "inventing" frames? Would love to hear your opinion here.

**Comment by mshin-wolvic** [comment]
> * Please remove the `Fixes #133` from the commit message as that refers to an internal tool. Future readers might be confused. Perhaps you could instead add the URL of the WebXR sample that you're using for testing

Maybe done(?)

> * Would it be possible to split it in two commits? One for the sync_frame_index_ changes and the other one for the pending_getframedata_ changes. I think they can be two different commits but please correct me if I'm wrong.

OK. I will split the patch soon.

> * I tested it and I wonder whether what we're doing is correct because it's "too good". All the other browsers (Wolvic Gecko, Meta browser) do suffer severe performance penalties because we're indeed skipping frames. However when testing this patch everything is supersmooth and we barely lose 10-20 FPS even moving the slider to 11 frames skipped. So I wonder whether we might be "inventing" frames? Would love to hear your opinion here.

Even though the new patch intentionally creates frame skips by JS, it feels like it has a higher fps than expected and the frames appear smoother. Other browsers, including the gecko-backend, appear to wait for 1 tick of vsync when trying to get the frame information like headset pos to create the new frame.
if applying the new patch, `wait` will not be released unless Frame Submit occurs when trying to get the frame information for a new frame. Then the new frame will be created with the previous the frame information. It's hard to see with the naked eye if the current frame is created with the old one. I'm not sure it would be OK to create the new frame with previous information. I think it's more proper to operate getting the frame info with 1 tick like other browsers for the intended frame skipping.

**Comment by svillar** [comment]
> > * Please remove the `Fixes #133` from the commit message as that refers to an internal tool. Future readers might be confused. Perhaps you could instead add the URL of the WebXR sample that you're using for testing
> 
> Maybe done(?)

I removed it from the PR description but you need to remove it from the commit message too.

> > * Would it be possible to split it in two commits? One for the sync_frame_index_ changes and the other one for the pending_getframedata_ changes. I think they can be two different commits but please correct me if I'm wrong.
> 
> OK. I will split the patch soon.

Thanks

> > * I tested it and I wonder whether what we're doing is correct because it's "too good". All the other browsers (Wolvic Gecko, Meta browser) do suffer severe performance penalties because we're indeed skipping frames. However when testing this patch everything is supersmooth and we barely lose 10-20 FPS even moving the slider to 11 frames skipped. So I wonder whether we might be "inventing" frames? Would love to hear your opinion here.
> 
> Even though the new patch intentionally creates frame skips by JS, it feels like it has a higher fps than expected and the frames appear smoother. Other browsers, including the gecko-backend, appear to wait for 1 tick of vsync when trying to get the frame information like headset pos to create the new frame. if applying the new patch, `wait` will not be released unless Frame Submit occurs when trying to get the frame information for a new frame. Then the new frame will be created with the previous the frame information. It's hard to see with the naked eye if the current frame is created with the old one. I'm not sure it would be OK to create the new frame with previous information. I think it's more proper to operate getting the frame info with 1 tick like other browsers for the intended frame skipping.

I didn't explain myself properly, I am not proposing to generate new frames using the old ones. What I say is that with this new patch the sample seems not to work properly because it's rendered very smootly, it's like no frame was skipped. Check what the Meta browser or Wolvic Gecko do. The FPS are drastically reduced and the whole rendering is choppy because we're indeed skipping frames. But with your patch it's like nothing happens. So I wonder whether we are doing something wrong (as it cannot be that good) or the other browsers are doing something wrong.

**Comment by mshin-wolvic** [comment]
> I didn't explain myself properly, I am not proposing to generate new frames using the old ones. What I say is that with this new patch the sample seems not to work properly because it's rendered very smootly, it's like no frame was skipped. Check what the Meta browser or Wolvic Gecko do. The FPS are drastically reduced and the whole rendering is choppy because we're indeed skipping frames. But with your patch it's like nothing happens. So I wonder whether we are doing something wrong (as it cannot be that good) or the other browsers are doing something wrong.

Ah! Sorry, I misinterpreted your point. I believe other browsers are right. This patch fixes the white flash issue only and I will fix the issue no reflecting the frame skip in another patch. I'm considering to use Wolvic Vsync's tick.

**Review by zakharvoit — APPROVED** [review]

**Pull request merged**
