### PR TITLE
Downcast ByteBuffer to Buffer

### PR DESCRIPTION
**Pull request by mshin-wolvic**
This CL solves the java error message, 'java.lang.NoSuchMethodError: No virtual method position(I)Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer;'.

In Java 8 used by Wolvic, the class ByteBuffer inherits the position method from the class Buffer and has a return type of java.nio.Buffer. On Java 11 and lather used by chromium, the method is overridden with an implementation that returns java.nio.ByteBuffer.

So, this changes to do explicitly the downcast from the class ByteBuffer to the class Buffer for the backward compatibility according to the Java version.

### CODE REVIEW

**Review by zakharvoit — APPROVED** [review]
Good find, looks good. We should revisit this when/if we update wolvic's JDK version.

**Review by duswnchl — APPROVED** [review]
LGTM!

**Comment by svillar** [comment]
I am not against this, but have you tried to bump the Wolvic dependencies to java11 first?

**Comment by mshin-wolvic** [comment]
> I am not against this, but have you tried to bump the Wolvic dependencies to java11 first?

Yes, there were too many build errors, and I didn't want to affect wolvic-gecko and reduce the cost of our effort.

**Review by jdapena — APPROVED** [review]

**Pull request merged**
