### PR TITLE
gpu: Increase texture size limit

### PR DESCRIPTION
**Pull request by tiagovignatti**
WebXR textures for VR experiences are naturally over 4k and this limitation is a problem on those cases.

We may want to adjust this to address such scenario and eventually upload to upstream.

### CODE REVIEW

**Review by jdapena — APPROVED** [review]
I would likely prefer to have special cases that drop this limit when we know GPU driver will support it properly.

In my experience many GPU drivers that are not that old still have a limit of 4096 for textures (or even less!). Is there any possibility that we actually use tiling?

**Review by svillar — CHANGES_REQUESTED** [review]
Same as for the other patch, I'm worried to allow sizes over that limit, drivers might crash and also worried about memory usage.

What happens when the texture size is larger than the limit? Could it be that we don't handle that case properly?

**Comment by tiagovignatti** [comment]
Like we've discussed offline, I have now increased the max texture size to a new limit. PTAL. Thank you.

**Review by svillar — CHANGES_REQUESTED** [review]
I'd prefer us to remove the workaround from the list of enabled workarounds and leave this untouched. Can we track the initialization of those enabled_workarounds?

**Comment by svillar** [comment]
> I'd prefer us to remove the workaround from the list of enabled workarounds and leave this untouched. Can we track the initialization of those enabled_workarounds?

Finally after some offline discussion we've decided to stick to the 16k limit which seems to be used everywhere else (Gecko, Meta's browser...)

**Pull request merged**
