### PR TITLE
wolvic: Enable disk cache

### PR DESCRIPTION
**Pull request by tiagovignatti**
This commit enables disk cache directory for the current user profile. To verify the correctness one can check that the index files are being created e.g.:

  $ adb shell run-as com.igalia.wolvic
  find -type f | grep Cache
  ./app_content_shell/content_shell/Cache/Cache_Data/*

This was tested with Oculus Quest 2 (Oculus API) and S21 (No API) devices.

Worth mentioning that Content Shell, in the upstream, could benefit from a very similar change in
content/shell/browser/shell_content_browser_client.cc.

### CODE REVIEW

**Comment by tiagovignatti** [comment]
hmm, I've sent the PR against `texture-limit` branch. So maybe I should fix that.

**Review by zakharvoit — APPROVED** [review]

**Review by svillar — APPROVED** [review]
Nice, but please do create it against the correct branch

**Comment by svillar** [comment]
> Nice, but please do create it against the correct branch

I could change the branch but then it logically pulls the other commits from the previous branch, so yeah I think you'd have to rebase.

**Comment by tiagovignatti** [comment]
Just like we have talked offline, I have now rebased (and force-pushed) this branch. PTAL. Thanks.

**Review by svillar — APPROVED** [review]
Nice!

**Pull request merged**
